-- Tier 0.6: CHECK constraints on state, type and money columns.
-- Generated from src/lib/db/constraints.ts by scripts/gen-constraints.ts — edit that file, not this one.

ALTER TABLE "UserRole" DROP CONSTRAINT IF EXISTS "chk_UserRole_role";
ALTER TABLE "UserRole" ADD CONSTRAINT "chk_UserRole_role" CHECK ("role" IN ('SALES_REP', 'REGIONAL_MANAGER', 'CONTRACTING_MANAGER', 'PRICING_ANALYST', 'PRICING_DIRECTOR', 'PRICING_COMMITTEE', 'PRODUCT_MARKETING', 'CLINICAL_REVIEWER', 'FINANCE', 'ADMIN', 'EXECUTIVE')) NOT VALID;
ALTER TABLE "UserRole" VALIDATE CONSTRAINT "chk_UserRole_role";
ALTER TABLE "Notification" DROP CONSTRAINT IF EXISTS "chk_Notification_kind";
ALTER TABLE "Notification" ADD CONSTRAINT "chk_Notification_kind" CHECK ("kind" IN ('RUN_COMPLETE', 'RUN_FAILED', 'APPROVAL_REQUESTED', 'APPROVAL_DECIDED', 'PROPOSAL_APPROVED', 'CROSS_PROPOSED', 'FEED_FAILED', 'ALERT', 'JOB_FAILED', 'BREAK_GLASS')) NOT VALID;
ALTER TABLE "Notification" VALIDATE CONSTRAINT "chk_Notification_kind";
ALTER TABLE "NotificationPreference" DROP CONSTRAINT IF EXISTS "chk_NotificationPreference_kind";
ALTER TABLE "NotificationPreference" ADD CONSTRAINT "chk_NotificationPreference_kind" CHECK ("kind" IN ('RUN_COMPLETE', 'RUN_FAILED', 'APPROVAL_REQUESTED', 'APPROVAL_DECIDED', 'PROPOSAL_APPROVED', 'CROSS_PROPOSED', 'FEED_FAILED', 'ALERT', 'JOB_FAILED', 'BREAK_GLASS', '*')) NOT VALID;
ALTER TABLE "NotificationPreference" VALIDATE CONSTRAINT "chk_NotificationPreference_kind";
ALTER TABLE "KnownCross" DROP CONSTRAINT IF EXISTS "chk_KnownCross_approvalStatus";
ALTER TABLE "KnownCross" ADD CONSTRAINT "chk_KnownCross_approvalStatus" CHECK ("approvalStatus" IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'RETIRED')) NOT VALID;
ALTER TABLE "KnownCross" VALIDATE CONSTRAINT "chk_KnownCross_approvalStatus";
ALTER TABLE "KnownCross" DROP CONSTRAINT IF EXISTS "chk_KnownCross_clinicalReviewStatus";
ALTER TABLE "KnownCross" ADD CONSTRAINT "chk_KnownCross_clinicalReviewStatus" CHECK ("clinicalReviewStatus" IN ('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED')) NOT VALID;
ALTER TABLE "KnownCross" VALIDATE CONSTRAINT "chk_KnownCross_clinicalReviewStatus";
ALTER TABLE "KnownCross" DROP CONSTRAINT IF EXISTS "chk_KnownCross_equivalenceLevel";
ALTER TABLE "KnownCross" ADD CONSTRAINT "chk_KnownCross_equivalenceLevel" CHECK ("equivalenceLevel" IN ('EXACT', 'FUNCTIONAL', 'CLOSEST_ALTERNATIVE', 'PREMIUM_ALTERNATIVE', 'PARTIAL_SUBSTITUTE', 'NONE')) NOT VALID;
ALTER TABLE "KnownCross" VALIDATE CONSTRAINT "chk_KnownCross_equivalenceLevel";
ALTER TABLE "ProposalLine" DROP CONSTRAINT IF EXISTS "chk_ProposalLine_equivalenceLevel";
ALTER TABLE "ProposalLine" ADD CONSTRAINT "chk_ProposalLine_equivalenceLevel" CHECK ("equivalenceLevel" IN ('EXACT', 'FUNCTIONAL', 'CLOSEST_ALTERNATIVE', 'PREMIUM_ALTERNATIVE', 'PARTIAL_SUBSTITUTE', 'NONE')) NOT VALID;
ALTER TABLE "ProposalLine" VALIDATE CONSTRAINT "chk_ProposalLine_equivalenceLevel";
ALTER TABLE "PriceEntry" DROP CONSTRAINT IF EXISTS "chk_PriceEntry_status";
ALTER TABLE "PriceEntry" ADD CONSTRAINT "chk_PriceEntry_status" CHECK ("status" IN ('ACTIVE', 'PENDING', 'EXPIRED', 'SUPERSEDED')) NOT VALID;
ALTER TABLE "PriceEntry" VALIDATE CONSTRAINT "chk_PriceEntry_status";
ALTER TABLE "PriceEntry" DROP CONSTRAINT IF EXISTS "chk_PriceEntry_approvalState";
ALTER TABLE "PriceEntry" ADD CONSTRAINT "chk_PriceEntry_approvalState" CHECK ("approvalState" IN ('APPROVED', 'PENDING', 'REJECTED')) NOT VALID;
ALTER TABLE "PriceEntry" VALIDATE CONSTRAINT "chk_PriceEntry_approvalState";
ALTER TABLE "Request" DROP CONSTRAINT IF EXISTS "chk_Request_status";
ALTER TABLE "Request" ADD CONSTRAINT "chk_Request_status" CHECK ("status" IN ('draft', 'queued', 'running', 'complete', 'failed', 'cancelled')) NOT VALID;
ALTER TABLE "Request" VALIDATE CONSTRAINT "chk_Request_status";
ALTER TABLE "RequestLine" DROP CONSTRAINT IF EXISTS "chk_RequestLine_resolutionStatus";
ALTER TABLE "RequestLine" ADD CONSTRAINT "chk_RequestLine_resolutionStatus" CHECK ("resolutionStatus" IN ('pending', 'resolved', 'not-found', 'error')) NOT VALID;
ALTER TABLE "RequestLine" VALIDATE CONSTRAINT "chk_RequestLine_resolutionStatus";
ALTER TABLE "RequestLine" DROP CONSTRAINT IF EXISTS "chk_RequestLine_matchStatus";
ALTER TABLE "RequestLine" ADD CONSTRAINT "chk_RequestLine_matchStatus" CHECK ("matchStatus" IN ('pending', 'matched', 'no-match', 'error')) NOT VALID;
ALTER TABLE "RequestLine" VALIDATE CONSTRAINT "chk_RequestLine_matchStatus";
ALTER TABLE "Account" DROP CONSTRAINT IF EXISTS "chk_Account_type";
ALTER TABLE "Account" ADD CONSTRAINT "chk_Account_type" CHECK ("type" IN ('SOLD_TO', 'SHIP_TO', 'BILL_TO', 'IDN', 'HEALTH_SYSTEM', 'GROUP', 'GPO_MEMBER')) NOT VALID;
ALTER TABLE "Account" VALIDATE CONSTRAINT "chk_Account_type";
ALTER TABLE "Contract" DROP CONSTRAINT IF EXISTS "chk_Contract_type";
ALTER TABLE "Contract" ADD CONSTRAINT "chk_Contract_type" CHECK ("type" IN ('LIST', 'GPO', 'IDN', 'LOCAL', 'NATIONAL')) NOT VALID;
ALTER TABLE "Contract" VALIDATE CONSTRAINT "chk_Contract_type";
ALTER TABLE "Contract" DROP CONSTRAINT IF EXISTS "chk_Contract_status";
ALTER TABLE "Contract" ADD CONSTRAINT "chk_Contract_status" CHECK ("status" IN ('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED', 'SUPERSEDED')) NOT VALID;
ALTER TABLE "Contract" VALIDATE CONSTRAINT "chk_Contract_status";
ALTER TABLE "RebateSchedule" DROP CONSTRAINT IF EXISTS "chk_RebateSchedule_type";
ALTER TABLE "RebateSchedule" ADD CONSTRAINT "chk_RebateSchedule_type" CHECK ("type" IN ('VOLUME', 'GROWTH', 'COMPLIANCE', 'FAMILY', 'BUNDLE')) NOT VALID;
ALTER TABLE "RebateSchedule" VALIDATE CONSTRAINT "chk_RebateSchedule_type";
ALTER TABLE "RebateSchedule" DROP CONSTRAINT IF EXISTS "chk_RebateSchedule_basis";
ALTER TABLE "RebateSchedule" ADD CONSTRAINT "chk_RebateSchedule_basis" CHECK ("basis" IN ('UNITS', 'VALUE', 'COMPLIANCE_PCT', 'GROWTH_PCT')) NOT VALID;
ALTER TABLE "RebateSchedule" VALIDATE CONSTRAINT "chk_RebateSchedule_basis";
ALTER TABLE "StandardCost" DROP CONSTRAINT IF EXISTS "chk_StandardCost_costType";
ALTER TABLE "StandardCost" ADD CONSTRAINT "chk_StandardCost_costType" CHECK ("costType" IN ('STANDARD', 'LANDED', 'TRANSFER')) NOT VALID;
ALTER TABLE "StandardCost" VALIDATE CONSTRAINT "chk_StandardCost_costType";
ALTER TABLE "Document" DROP CONSTRAINT IF EXISTS "chk_Document_kind";
ALTER TABLE "Document" ADD CONSTRAINT "chk_Document_kind" CHECK ("kind" IN ('INVOICE', 'PO', 'BID_FILE', 'CONTRACT', 'COMPETITOR_LIST', 'OTHER')) NOT VALID;
ALTER TABLE "Document" VALIDATE CONSTRAINT "chk_Document_kind";
ALTER TABLE "CompetitorPriceObservation" DROP CONSTRAINT IF EXISTS "chk_CompetitorPriceObservation_sourceType";
ALTER TABLE "CompetitorPriceObservation" ADD CONSTRAINT "chk_CompetitorPriceObservation_sourceType" CHECK ("sourceType" IN ('CUSTOMER_INVOICE', 'CUSTOMER_PO', 'CUSTOMER_BID_FILE', 'GPO_CONTRACT_FILE', 'WIN_LOSS_RECORD', 'INTERNAL_VERIFIED', 'PUBLIC_BID_DB', 'REP_OBSERVED', 'ANECDOTAL')) NOT VALID;
ALTER TABLE "CompetitorPriceObservation" VALIDATE CONSTRAINT "chk_CompetitorPriceObservation_sourceType";
ALTER TABLE "CompetitorPriceObservation" DROP CONSTRAINT IF EXISTS "chk_CompetitorPriceObservation_verificationStatus";
ALTER TABLE "CompetitorPriceObservation" ADD CONSTRAINT "chk_CompetitorPriceObservation_verificationStatus" CHECK ("verificationStatus" IN ('UNVERIFIED', 'VERIFIED', 'DISPUTED')) NOT VALID;
ALTER TABLE "CompetitorPriceObservation" VALIDATE CONSTRAINT "chk_CompetitorPriceObservation_verificationStatus";
ALTER TABLE "PricingPolicy" DROP CONSTRAINT IF EXISTS "chk_PricingPolicy_status";
ALTER TABLE "PricingPolicy" ADD CONSTRAINT "chk_PricingPolicy_status" CHECK ("status" IN ('DRAFT', 'ACTIVE', 'SUPERSEDED')) NOT VALID;
ALTER TABLE "PricingPolicy" VALIDATE CONSTRAINT "chk_PricingPolicy_status";
ALTER TABLE "PricingPolicy" DROP CONSTRAINT IF EXISTS "chk_PricingPolicy_floorMethod";
ALTER TABLE "PricingPolicy" ADD CONSTRAINT "chk_PricingPolicy_floorMethod" CHECK ("floorMethod" IN ('COST_PLUS_MIN_MARGIN', 'PCT_OF_LIST', 'FIXED')) NOT VALID;
ALTER TABLE "PricingPolicy" VALIDATE CONSTRAINT "chk_PricingPolicy_floorMethod";
ALTER TABLE "PricingPolicy" DROP CONSTRAINT IF EXISTS "chk_PricingPolicy_defaultStrategy";
ALTER TABLE "PricingPolicy" ADD CONSTRAINT "chk_PricingPolicy_defaultStrategy" CHECK ("defaultStrategy" IN ('MATCH', 'UNDERCUT_AMOUNT', 'UNDERCUT_PCT', 'HOLD_PREMIUM', 'PRESERVE_CONTRACT', 'STRATEGIC_DISCOUNT', 'PENETRATION')) NOT VALID;
ALTER TABLE "PricingPolicy" VALIDATE CONSTRAINT "chk_PricingPolicy_defaultStrategy";
ALTER TABLE "PricingPolicy" DROP CONSTRAINT IF EXISTS "chk_PricingPolicy_classification";
ALTER TABLE "PricingPolicy" ADD CONSTRAINT "chk_PricingPolicy_classification" CHECK ("classification" IN ('COMMODITY', 'DIFFERENTIATED')) NOT VALID;
ALTER TABLE "PricingPolicy" VALIDATE CONSTRAINT "chk_PricingPolicy_classification";
ALTER TABLE "Proposal" DROP CONSTRAINT IF EXISTS "chk_Proposal_status";
ALTER TABLE "Proposal" ADD CONSTRAINT "chk_Proposal_status" CHECK ("status" IN ('DRAFT', 'APPROVAL_REQUIRED', 'SUBMITTED', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'EXPIRED', 'WON', 'LOST')) NOT VALID;
ALTER TABLE "Proposal" VALIDATE CONSTRAINT "chk_Proposal_status";
ALTER TABLE "Proposal" DROP CONSTRAINT IF EXISTS "chk_Proposal_freightMode";
ALTER TABLE "Proposal" ADD CONSTRAINT "chk_Proposal_freightMode" CHECK ("freightMode" IN ('NONE', 'FLAT', 'PCT')) NOT VALID;
ALTER TABLE "Proposal" VALIDATE CONSTRAINT "chk_Proposal_freightMode";
ALTER TABLE "Proposal" DROP CONSTRAINT IF EXISTS "chk_Proposal_taxMode";
ALTER TABLE "Proposal" ADD CONSTRAINT "chk_Proposal_taxMode" CHECK ("taxMode" IN ('NONE', 'EXEMPT', 'MANUAL', 'PROVIDER')) NOT VALID;
ALTER TABLE "Proposal" VALIDATE CONSTRAINT "chk_Proposal_taxMode";
ALTER TABLE "ProposalLine" DROP CONSTRAINT IF EXISTS "chk_ProposalLine_contractPriceSource";
ALTER TABLE "ProposalLine" ADD CONSTRAINT "chk_ProposalLine_contractPriceSource" CHECK ("contractPriceSource" IN ('LIST', 'GPO', 'IDN', 'LOCAL', 'NATIONAL')) NOT VALID;
ALTER TABLE "ProposalLine" VALIDATE CONSTRAINT "chk_ProposalLine_contractPriceSource";
ALTER TABLE "ProposalLine" DROP CONSTRAINT IF EXISTS "chk_ProposalLine_competitorPriceBasis";
ALTER TABLE "ProposalLine" ADD CONSTRAINT "chk_ProposalLine_competitorPriceBasis" CHECK ("competitorPriceBasis" IN ('KNOWN_ACCOUNT', 'MARKET_ESTIMATE', 'WEAK', 'NONE')) NOT VALID;
ALTER TABLE "ProposalLine" VALIDATE CONSTRAINT "chk_ProposalLine_competitorPriceBasis";
ALTER TABLE "ProposalLine" DROP CONSTRAINT IF EXISTS "chk_ProposalLine_approvalState";
ALTER TABLE "ProposalLine" ADD CONSTRAINT "chk_ProposalLine_approvalState" CHECK ("approvalState" IN ('NOT_REQUIRED', 'REQUIRED', 'PENDING', 'APPROVED', 'REJECTED')) NOT VALID;
ALTER TABLE "ProposalLine" VALIDATE CONSTRAINT "chk_ProposalLine_approvalState";
ALTER TABLE "Scenario" DROP CONSTRAINT IF EXISTS "chk_Scenario_kind";
ALTER TABLE "Scenario" ADD CONSTRAINT "chk_Scenario_kind" CHECK ("kind" IN ('RECOMMENDED', 'AGGRESSIVE', 'MARGIN_OPTIMIZED', 'CUSTOMER_REQUESTED', 'CUSTOM', 'FINAL')) NOT VALID;
ALTER TABLE "Scenario" VALIDATE CONSTRAINT "chk_Scenario_kind";
ALTER TABLE "ApprovalRequest" DROP CONSTRAINT IF EXISTS "chk_ApprovalRequest_status";
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "chk_ApprovalRequest_status" CHECK ("status" IN ('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'WITHDRAWN', 'EXPIRED')) NOT VALID;
ALTER TABLE "ApprovalRequest" VALIDATE CONSTRAINT "chk_ApprovalRequest_status";
ALTER TABLE "CrosswalkVersion" DROP CONSTRAINT IF EXISTS "chk_CrosswalkVersion_status";
ALTER TABLE "CrosswalkVersion" ADD CONSTRAINT "chk_CrosswalkVersion_status" CHECK ("status" IN ('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'SUPERSEDED', 'RETIRED')) NOT VALID;
ALTER TABLE "CrosswalkVersion" VALIDATE CONSTRAINT "chk_CrosswalkVersion_status";
ALTER TABLE "SyncLog" DROP CONSTRAINT IF EXISTS "chk_SyncLog_direction";
ALTER TABLE "SyncLog" ADD CONSTRAINT "chk_SyncLog_direction" CHECK ("direction" IN ('IN', 'OUT')) NOT VALID;
ALTER TABLE "SyncLog" VALIDATE CONSTRAINT "chk_SyncLog_direction";
ALTER TABLE "SyncLog" DROP CONSTRAINT IF EXISTS "chk_SyncLog_status";
ALTER TABLE "SyncLog" ADD CONSTRAINT "chk_SyncLog_status" CHECK ("status" IN ('OK', 'RETRY', 'FAILED', 'SKIPPED')) NOT VALID;
ALTER TABLE "SyncLog" VALIDATE CONSTRAINT "chk_SyncLog_status";
ALTER TABLE "DealOutcome" DROP CONSTRAINT IF EXISTS "chk_DealOutcome_outcome";
ALTER TABLE "DealOutcome" ADD CONSTRAINT "chk_DealOutcome_outcome" CHECK ("outcome" IN ('WON', 'LOST', 'NO_DECISION')) NOT VALID;
ALTER TABLE "DealOutcome" VALIDATE CONSTRAINT "chk_DealOutcome_outcome";
ALTER TABLE "MatchDecision" DROP CONSTRAINT IF EXISTS "chk_MatchDecision_groundTruth";
ALTER TABLE "MatchDecision" ADD CONSTRAINT "chk_MatchDecision_groundTruth" CHECK ("groundTruth" IN ('VALIDATED_CORRECT', 'VALIDATED_INCORRECT', 'UNKNOWN')) NOT VALID;
ALTER TABLE "MatchDecision" VALIDATE CONSTRAINT "chk_MatchDecision_groundTruth";
ALTER TABLE "GudidImport" DROP CONSTRAINT IF EXISTS "chk_GudidImport_status";
ALTER TABLE "GudidImport" ADD CONSTRAINT "chk_GudidImport_status" CHECK ("status" IN ('QUEUED', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED')) NOT VALID;
ALTER TABLE "GudidImport" VALIDATE CONSTRAINT "chk_GudidImport_status";
ALTER TABLE "Alert" DROP CONSTRAINT IF EXISTS "chk_Alert_severity";
ALTER TABLE "Alert" ADD CONSTRAINT "chk_Alert_severity" CHECK ("severity" IN ('INFO', 'WARNING', 'CRITICAL')) NOT VALID;
ALTER TABLE "Alert" VALIDATE CONSTRAINT "chk_Alert_severity";
ALTER TABLE "FeedRun" DROP CONSTRAINT IF EXISTS "chk_FeedRun_trigger";
ALTER TABLE "FeedRun" ADD CONSTRAINT "chk_FeedRun_trigger" CHECK ("trigger" IN ('schedule', 'manual', 'startup')) NOT VALID;
ALTER TABLE "FeedRun" VALIDATE CONSTRAINT "chk_FeedRun_trigger";
ALTER TABLE "FeedRun" DROP CONSTRAINT IF EXISTS "chk_FeedRun_status";
ALTER TABLE "FeedRun" ADD CONSTRAINT "chk_FeedRun_status" CHECK ("status" IN ('RUNNING', 'OK', 'FAILED', 'SKIPPED')) NOT VALID;
ALTER TABLE "FeedRun" VALIDATE CONSTRAINT "chk_FeedRun_status";
ALTER TABLE "AnalyticsSnapshot" DROP CONSTRAINT IF EXISTS "chk_AnalyticsSnapshot_trigger";
ALTER TABLE "AnalyticsSnapshot" ADD CONSTRAINT "chk_AnalyticsSnapshot_trigger" CHECK ("trigger" IN ('schedule', 'event', 'manual')) NOT VALID;
ALTER TABLE "AnalyticsSnapshot" VALIDATE CONSTRAINT "chk_AnalyticsSnapshot_trigger";
ALTER TABLE "PublicAward" DROP CONSTRAINT IF EXISTS "chk_PublicAward_source";
ALTER TABLE "PublicAward" ADD CONSTRAINT "chk_PublicAward_source" CHECK ("source" IN ('SAM', 'USASPENDING', 'BIDFILE')) NOT VALID;
ALTER TABLE "PublicAward" VALIDATE CONSTRAINT "chk_PublicAward_source";
ALTER TABLE "RequestLine" DROP CONSTRAINT IF EXISTS "chk_RequestLine_quantity_nonneg";
ALTER TABLE "RequestLine" ADD CONSTRAINT "chk_RequestLine_quantity_nonneg" CHECK ("quantity" >= 0) NOT VALID;
ALTER TABLE "RequestLine" VALIDATE CONSTRAINT "chk_RequestLine_quantity_nonneg";
ALTER TABLE "ProposalLine" DROP CONSTRAINT IF EXISTS "chk_ProposalLine_quantity_nonneg";
ALTER TABLE "ProposalLine" ADD CONSTRAINT "chk_ProposalLine_quantity_nonneg" CHECK ("quantity" >= 0) NOT VALID;
ALTER TABLE "ProposalLine" VALIDATE CONSTRAINT "chk_ProposalLine_quantity_nonneg";
ALTER TABLE "ProposalLine" DROP CONSTRAINT IF EXISTS "chk_ProposalLine_prices_nonneg";
ALTER TABLE "ProposalLine" ADD CONSTRAINT "chk_ProposalLine_prices_nonneg" CHECK (("proposedPrice" IS NULL OR "proposedPrice" >= 0) AND ("listPrice" IS NULL OR "listPrice" >= 0) AND ("floorPrice" IS NULL OR "floorPrice" >= 0) AND ("recommendedPrice" IS NULL OR "recommendedPrice" >= 0)) NOT VALID;
ALTER TABLE "ProposalLine" VALIDATE CONSTRAINT "chk_ProposalLine_prices_nonneg";
ALTER TABLE "PriceEntry" DROP CONSTRAINT IF EXISTS "chk_PriceEntry_price_nonneg";
ALTER TABLE "PriceEntry" ADD CONSTRAINT "chk_PriceEntry_price_nonneg" CHECK ("price" >= 0) NOT VALID;
ALTER TABLE "PriceEntry" VALIDATE CONSTRAINT "chk_PriceEntry_price_nonneg";
ALTER TABLE "PriceEntry" DROP CONSTRAINT IF EXISTS "chk_PriceEntry_qty_band";
ALTER TABLE "PriceEntry" ADD CONSTRAINT "chk_PriceEntry_qty_band" CHECK ("minQty" IS NULL OR "maxQty" IS NULL OR "maxQty" >= "minQty") NOT VALID;
ALTER TABLE "PriceEntry" VALIDATE CONSTRAINT "chk_PriceEntry_qty_band";
ALTER TABLE "PurchaseRecord" DROP CONSTRAINT IF EXISTS "chk_PurchaseRecord_netprice_nonneg";
ALTER TABLE "PurchaseRecord" ADD CONSTRAINT "chk_PurchaseRecord_netprice_nonneg" CHECK ("netPrice" >= 0) NOT VALID;
ALTER TABLE "PurchaseRecord" VALIDATE CONSTRAINT "chk_PurchaseRecord_netprice_nonneg";
ALTER TABLE "CompetitorPriceObservation" DROP CONSTRAINT IF EXISTS "chk_CompetitorPriceObservation_price_nonneg";
ALTER TABLE "CompetitorPriceObservation" ADD CONSTRAINT "chk_CompetitorPriceObservation_price_nonneg" CHECK ("price" >= 0) NOT VALID;
ALTER TABLE "CompetitorPriceObservation" VALIDATE CONSTRAINT "chk_CompetitorPriceObservation_price_nonneg";
ALTER TABLE "StandardCost" DROP CONSTRAINT IF EXISTS "chk_StandardCost_cost_nonneg";
ALTER TABLE "StandardCost" ADD CONSTRAINT "chk_StandardCost_cost_nonneg" CHECK ("cost" >= 0) NOT VALID;
ALTER TABLE "StandardCost" VALIDATE CONSTRAINT "chk_StandardCost_cost_nonneg";
ALTER TABLE "PricingPolicy" DROP CONSTRAINT IF EXISTS "chk_PricingPolicy_margin_fraction";
ALTER TABLE "PricingPolicy" ADD CONSTRAINT "chk_PricingPolicy_margin_fraction" CHECK ("targetMarginPct" >= 0 AND "targetMarginPct" <= 1 AND "minMarginPct" >= 0 AND "minMarginPct" <= 1) NOT VALID;
ALTER TABLE "PricingPolicy" VALIDATE CONSTRAINT "chk_PricingPolicy_margin_fraction";
ALTER TABLE "Proposal" DROP CONSTRAINT IF EXISTS "chk_Proposal_freight_value";
ALTER TABLE "Proposal" ADD CONSTRAINT "chk_Proposal_freight_value" CHECK ("freightValue" IS NULL OR ("freightValue" >= 0 AND ("freightMode" <> 'PCT' OR "freightValue" <= 100))) NOT VALID;
ALTER TABLE "Proposal" VALIDATE CONSTRAINT "chk_Proposal_freight_value";
ALTER TABLE "Proposal" DROP CONSTRAINT IF EXISTS "chk_Proposal_tax_amount_nonneg";
ALTER TABLE "Proposal" ADD CONSTRAINT "chk_Proposal_tax_amount_nonneg" CHECK ("taxAmount" IS NULL OR "taxAmount" >= 0) NOT VALID;
ALTER TABLE "Proposal" VALIDATE CONSTRAINT "chk_Proposal_tax_amount_nonneg";
ALTER TABLE "Contract" DROP CONSTRAINT IF EXISTS "chk_Contract_term_order";
ALTER TABLE "Contract" ADD CONSTRAINT "chk_Contract_term_order" CHECK ("effectiveTo" IS NULL OR "effectiveTo" >= "effectiveFrom") NOT VALID;
ALTER TABLE "Contract" VALIDATE CONSTRAINT "chk_Contract_term_order";
ALTER TABLE "GpoMembership" DROP CONSTRAINT IF EXISTS "chk_GpoMembership_term_order";
ALTER TABLE "GpoMembership" ADD CONSTRAINT "chk_GpoMembership_term_order" CHECK ("effectiveTo" IS NULL OR "effectiveTo" >= "effectiveFrom") NOT VALID;
ALTER TABLE "GpoMembership" VALIDATE CONSTRAINT "chk_GpoMembership_term_order";
ALTER TABLE "PriceEntry" DROP CONSTRAINT IF EXISTS "chk_PriceEntry_term_order";
ALTER TABLE "PriceEntry" ADD CONSTRAINT "chk_PriceEntry_term_order" CHECK ("effectiveTo" IS NULL OR "effectiveTo" >= "effectiveFrom") NOT VALID;
ALTER TABLE "PriceEntry" VALIDATE CONSTRAINT "chk_PriceEntry_term_order";
ALTER TABLE "ApprovalDelegation" DROP CONSTRAINT IF EXISTS "chk_ApprovalDelegation_window_order";
ALTER TABLE "ApprovalDelegation" ADD CONSTRAINT "chk_ApprovalDelegation_window_order" CHECK ("endsAt" > "startsAt") NOT VALID;
ALTER TABLE "ApprovalDelegation" VALIDATE CONSTRAINT "chk_ApprovalDelegation_window_order";
