import { parseAccessSizes, buildAccessProfile, lengthClassOf } from "@/lib/match/access";
import { brandAssertions } from "@/lib/match/brands";
import { compareAccess } from "@/lib/match/constraints";
const P = (t: string) => { const r = parseAccessSizes(t); return `d=${JSON.stringify(r.diameters)} r=${r.range ? `${r.range.min}-${r.range.max}` : null} l=${r.lengthMm} lc=${r.lengthClass} fr=${r.diameterFromRange}`; };
for (const t of ["12 × 100 mm", "12mm x 100mm", "100 mm x 11 mm", "5x95", "5x95 trocar", "5–12 mm", "5-12mm", "5 mm to 12 mm", "instruments up to 11 mm", "2/3 mm", "2 mm/3 mm", "5/10 mm", "12 mm trocar, Box of 6", "12 mm trocar 6/bx", "6/bx 12 mm trocar", "Box of 6 12 mm trocars", "5 mm trocar with 5 - 2/3 mm reducer", "10 mm trocar and 5 - 10 mm reducer", "12 mm trocar; 5 mm reducer cap", "trocar 80 mm", "trocar 81 mm", "trocar 120 mm", "trocar 121 mm", "10 cm length trocar 12 mm", "12 mm x 10 cm", "12 mm trocar 4 inch", "3 x 12 mm"]) console.log(t.padEnd(44), P(t));
console.log("lengthClassOf", [80, 80.5, 81, 120, 120.5, 121].map((v) => `${v}=${lengthClassOf(v)}`).join(" "));
const prof = (sizes: { type?: string; value?: string; unit?: string }[] | null, dims: { name: string; value: number; unit: string }[] | null) => { const p = buildAccessProfile([{ text: null, source: "curated-spec", dims }, { text: null, source: "gudid:size", sizes }, { text: "12 mm trocar", source: "gudid:description" }]); return `d=${JSON.stringify(p.diameters)} l=${p.lengthMm} lc=${p.lengthClass} ev=${p.evidence.map((e) => e.field + ":" + e.value + "@" + e.source).join(",")}`; };
console.log("gudid cm length:", prof([{ type: "Length", value: "10", unit: "Centimeter" }], null));
console.log("curated cm:", prof(null, [{ name: "diameter", value: 1.2, unit: "cm" }, { name: "length", value: 10, unit: "cm" }]));
console.log("curated in:", prof(null, [{ name: "length", value: 4, unit: "in" }]));
console.log("gudid other unit:", prof([{ type: "Length", value: "100", unit: "French" }], null));
for (const t of ["non-optical trocar", "trocar without fixation", "Non-Threaded cannula", "OPTIVIEW", "OPTIVIEW Ethicon", "VersaStep needle", "VersaStep Plus 12 mm", "Kii Fios First Entry", "Kii Shielded Bladed", "Kii Balloon Blunt Tip", "Kii Sleeve", "Kii Advanced Fixation Cannula", "Kii Access System 5 x 100", "non-bladed trocar", "bladed-less", "smooth, non-threaded", "optical-less"]) console.log(t.padEnd(32), brandAssertions(t).map((a) => `${a.key}:${JSON.stringify(a.assert).slice(0, 60)}`).join(" | "));
const mk = (over: Partial<ReturnType<typeof buildAccessProfile>>) => ({ ...buildAccessProfile([]), ...over });
const c = (a: Partial<ReturnType<typeof buildAccessProfile>>, b: Partial<ReturnType<typeof buildAccessProfile>>) => { const r = compareAccess(mk(a), mk(b)); return `cap=${r.cap} mult=${r.multiplier.toFixed(3)} cov=${r.coverage} attr=${r.attributeCap} hard=${r.hard} soft=${r.soft} conf=${r.diameterConfirmed}`; };
console.log("dia 12 vs 12.5:", c({ diameters: [12] }, { diameters: [12.5] }));
console.log("dia 12 vs 12.51:", c({ diameters: [12] }, { diameters: [12.51] }));
console.log("dia 12 vs 11.5:", c({ diameters: [12] }, { diameters: [11.5] }));
console.log("cannula vs trocar:", c({ component: "cannula" }, { component: "trocar" }));
console.log("dilating vs trocar full:", c({ component: "trocar", diameters: [12], lengthClass: "standard", visualization: "non-optical", tip: "bladeless" }, { component: "dilating-system", diameters: [12], lengthClass: "standard", visualization: "non-optical", tip: "bladeless" }));
console.log("coverage 3/5:", c({ component: "trocar", diameters: [12], lengthClass: "standard" }, { component: "trocar", diameters: [12], lengthClass: "standard" }));
console.log("coverage 4/5:", c({ component: "trocar", diameters: [12], lengthClass: "standard", tip: "bladeless" }, { component: "trocar", diameters: [12], lengthClass: "standard", tip: "bladeless" }));
console.log("optical vs unknown:", c({ component: "trocar", diameters: [12], lengthClass: "standard", tip: "bladeless", visualization: "optical" }, { component: "trocar", diameters: [12], lengthClass: "standard", tip: "bladeless" }));
console.log("unknown both:", c({}, {}));
